apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres_ds
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    database: predictions
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false