{
 "title": "Ingestion Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Files Ingested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(*) AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Avg Valid %",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(\n        (AVG(n_valid::numeric / NULLIF(n_rows,0)) * 100)::numeric,\n        2\n    ) AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Avg Invalid %",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(\n        (AVG(n_invalid::numeric / NULLIF(n_rows,0)) * 100)::numeric,\n        2\n    ) AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Valid Rows (%) Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n    created_at AS time,\n    (n_valid::numeric / NULLIF(n_rows, 0)) * 100 AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY created_at;\n"
    }
   ]
  },
  {
   "title": "Invalid Rows (%) Trend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    created_at AS time,\n    (n_invalid::numeric / NULLIF(n_rows, 0)) * 100 AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY created_at;\n"
    }
   ]
  },
  {
   "title": "Severity Over Time (0=none, 1=low, 2=medium, 3=high)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    created_at AS time,\n    CASE \n        WHEN severity = 'high' THEN 3\n        WHEN severity = 'medium' THEN 2\n        WHEN severity = 'low' THEN 1\n        ELSE 0\n    END::numeric AS value\nFROM ingestion_stats\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY created_at;\n"
    }
   ]
  },
  {
   "title": "Files Ingested per Minute - Last 10 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', created_at) AS time, COUNT(*) AS value FROM ingestion_stats WHERE created_at BETWEEN $__timeFrom() AND $__timeTo() GROUP BY 1 ORDER BY 1;"
    }
   ]
  }
 ]
}